# Generated by Django 4.0.4 on 2023-01-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesWebpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
