# Generated by Django 4.0.4 on 2023-01-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesWebpage', '0002_cartdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='author',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
