# Generated by Django 4.0.4 on 2023-01-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesWebpage', '0003_remove_cartdb_author_cartdb_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
